export const serviceProviders = [
  {
    id: 1,
    name: 'Aluguel de Mesas e Cadeiras',
    city: 'Rio de Janeiro',
    serviceType: 'Aluguel de Móveis',
    img: 'https://picsum.photos/300/250.webp?random=11',
  },
  {
    id: 2,
    name: 'Buffet Gourmet',
    city: 'São Paulo',
    serviceType: 'Buffet para Eventos',
    img: 'https://picsum.photos/300/250.webp?random=12',
  },
  {
    id: 3,
    name: 'Aluguel de Barracas',
    city: 'Belo Horizonte',
    serviceType: 'Aluguel de Estruturas',
    img: 'https://picsum.photos/300/250.webp?random=13',
  },
  {
    id: 4,
    name: 'Buffet Infantil',
    city: 'Curitiba',
    serviceType: 'Buffet Infantil',
    img: 'https://picsum.photos/300/250.webp?random=14',
  },
  {
    id: 5,
    name: 'Tendas Festas',
    city: 'Brasília',
    serviceType: 'Aluguel de Tendas',
    img: 'https://picsum.photos/300/250.webp?random=15',
  },
  {
    id: 6,
    name: 'Decoração de Eventos',
    city: 'Fortaleza',
    serviceType: 'Decoração para Festas',
    img: 'https://picsum.photos/300/250.webp?random=16',
  },
  {
    id: 7,
    name: 'Som e Luzes',
    city: 'Porto Alegre',
    serviceType: 'Aluguel de Equipamentos de Som e Luz',
    img: 'https://picsum.photos/300/250.webp?random=17',
  },
  {
    id: 8,
    name: 'Doces e Bolos',
    city: 'Recife',
    serviceType: 'Buffet de Doces e Bolos',
    img: 'https://picsum.photos/300/250.webp?random=18',
  },
  {
    id: 9,
    name: 'Locação de Louças',
    city: 'Salvador',
    serviceType: 'Aluguel de Louças e Utensílios',
    img: 'https://picsum.photos/300/250.webp?random=19',
  },
  {
    id: 10,
    name: 'Buffet Completo',
    city: 'Manaus',
    serviceType: 'Buffet Completo',
    img: 'https://picsum.photos/300/250.webp?random=20',
  },
];